### ISSUE TITLE
Usage documentation outside of Heroku

### ISSUE THREAD

**Issue by skynet** [heroku/awsdetailedbilling#4]
How do you run this outside of Heroku, e.g. on a regular EC2 instance at AWS and with npm (not iojs)? Your usage sample is ``heroku run -s PX "iojs import_finalized.js"`
Deployed with `npm install awsdetailedbilling`

**Comment by idan** [comment]
@skynet sorry, didn't notice this issue.

This is not available on npm, nor is it made to run on an EC2 instance.

**Comment by skynet** [comment]
tx
